title: Silas Kidd
email: silaskidd@gmail.com
description: > # Thoughts of a madman
baseurl: "/blog" 
url: "http://www.silaskidd.com"
twitter_username: silasjk
github_username:  silasjk
markdown: kramdown
